website/config.js, website/index.html, website/scripts/app.js
Closes #19 
So not sure if this was what you had in mind, but at least now it's in a separate file - no build system.
=> Make baseUrl, sslProxyUrl and apiKey configurable

website/scripts/app.js
`getQueryParameter` will search for a specific parameter name, return the value if found, or `false` otherwise.
=> improved parameter fetching functionality

website/scripts/app.js, website/scripts/audioManager.js
=> Indicate currently playing episode

README.md, podcast-feed-loader/package-lock.json, podcast-feed-loader/package.json, podcast-feed-loader/src/errorMonitoring.js, podcast-feed-loader/src/multiUrlLoader.js
Will log errors with Airbrake if you have environment variables set, otherwise will log errors to console.
=> Setting up optional error monitoring for feed loader

.gitignore, website-react/public/index.html, website-react/src/models/AudioPlayerModel.js, website-react/src/models/SearchModel.js
It's not very elegant, so I updated #47 to include abstracting it better. Is there was a more react-y way to handle a cross cutting concern like this.
Should the tracking be done in another model? Maybe there's a notion of a helper?
Fixes #62
=> Event tracking

website-react/package.json, website-react/public/sw.js, website-react/updateBuildCacheVersion.js
Not a great solution, but will get us over the hump till there's a more mature CI/CD process
=> Dynamic cache name

website-react/src/App.js, website-react/src/assets/back10.svg, website-react/src/assets/forward30.svg, website-react/src/assets/pause.svg, website-react/src/assets/play.svg, website-react/src/components/Player/AudioPlayer.js, website-react/src/components/Player/NowPlaying.js
This should make implementation of <audio> feel consistent across all browsers. This change includes a Play/pause button, forward/backward skip buttons, and a text-based progress indicator.
=> First pass at custom audio player

podcast-feed-loader/app/data/feeds.json, podcast-feed-loader/app/src/feedToSearchAdapter.js, podcast-feed-loader/app/src/urlParser.js, podcast-feed-loader/app/tests/feedToSearchAdapter.spec.js
Adding more shows, removing a couple that can't currently be proxied (see #86)
=> More shows

website-react/src/App.js, website-react/src/components/Main/Card.js, website-react/src/components/Player/AudioPlayer.js, website-react/src/components/Player/NowPlaying.js, website-react/src/components/Player/TimeSlider.js, website-react/src/config.js, website-react/src/helpers.js, website-react/src/index.css, website-react/src/models/AudioPlayerModel.js
Some side effects with this feature: I renamed `playbackRate` to `playbackrate` because it was throwing errors in the console. I also made the Card div stretch the full-height of the screen, for a smoother look when the queue is empty.
Otherwise, this PR is all about scrubbin'!
=> Scrub a dub dub

website-react/src/components/Player/TimeSlider.js
This is intended to increase the readability of the TimeSlider component and cut out some of the code duplication around event handlers
=> TimeSlider cleanup

.travis.yml, README.md, package.json, website-react/cypress/integration/playlist.spec.js, website-react/cypress/integration/search.spec.js, website-react/cypress/support/index.js, website-react/package.json
=> Adding e2e to pipe

.gitignore, website-react/src/components/Header/Search.js, website-react/src/components/Main/Episode/PodcastReleaseDate.js, website-react/src/components/Main/Queue.js, website-react/src/components/Main/SearchResults.js
Closes #140 
Not sure if the style for the placeholder text is quite right, but I hope the rest of you agree it should be different in some way. Usually placeholder text will be a bit transparent - for now I've just changed the color.
=> Change placeholder styling + add dates to episode cards

website-react/src/components/Main/SearchResults.js
Fixed the issue of  narrowing result items (#146) by updating setting search container width to `100vw`.
=> Fixed issue of narrowing result items - #146

podcast-feed-loader/app/src/updaters/azure/schemaDefinition.js, website-react/cypress/integration/config.js, website-react/cypress/integration/main.spec.js, website-react/cypress/integration/playlist.spec.js, website-react/cypress/integration/search.spec.js, website-react/src/config.js, website-react/src/models/SearchModel.js
=> Allowing for Search suffixes

website-react/cypress.json, website-react/src/config.js
Closes #141 
Sorts search results by release date.
=> Order search results by episode published date

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
For both templates
1. Bug report
1. Feature request
=> Added emojis to issue templates

.travis.yml, website-react/cypress.json
Added the Cypress branch to be built by TravisCI to help with cache/race condition debugging.
Closes #165
=> Closing #165 and adding Cypress branch to TravisCI builds

website-react/src/components/Main/Episode/DragNDropIndicator.js
Fix PlayList drag & drop issue on firefox #174
=> Fix drag firefox 174

README.md
* Added the MIT license badge.
* Updated existing badges to be a more consistent color (green) and shape (default).
=> README Badge Update

website-react/src/components/Main/SearchResults.js, website-react/src/config.js, website-react/src/models/SearchModel.js
=> Indicate if search results have been limited

website-react/src/components/Header/Search.js, website-react/src/models/SearchModel.js
=> Fix for issue #201

website-react/src/components/Header/Search.js
Fix for #217, I added an aria-label to the input element.
=> Added an aria-label attribute to the podcast search input for a11y.

.github/ISSUE_TEMPLATE/accessibility--a11y--issue.md
=> Update issue templates - a11y

website-react/src/components/Main/Queue.js
=> adding <li> element around the default empty search text for a11y.

website-react/src/components/Main/SearchResults.js
Search results were in `<li>` elements but they did not have an outer list container element.  I added an `<ul>` wrapper.  Thanks @dance2die for helping with the final solution.
Please squash the merge. Closes #225
=> Fix for Issue 225

website-react/src/components/Player/Slider.js
=> Changed Scrubber <radialGradient> element to use class instead of ID.

website-react/package-lock.json, website-react/src/components/Header/Search.js, website-react/src/components/Main/SearchResults.js
So, I managed to do what was asked for in #250 
Let me know if it's not the most optimal way. 
I was limited with options because the same searchTerm was used at 3-4 (search api and results) different places so had to change another file.
=> Accurate search results

.travis.yml, README.md, website/cypress/integration/queue.spec.js, website/package-lock.json, website/package.json
Changes that "should" fix travis.
=> Cypress fix

package-lock.json, website/package-lock.json, website/package.json, website/src/__tests__/App.test.js, website/src/__tests__/sw.test.js, website/src/sw.js
Updating for needed testing items (for me).
=> Basic tests moved, jest-dom and service-worker-mock added.

README.md
Added the following badges:
* Ruby version
* Rails version
=> Updated README.md with more badges

.travis.yml, README.md, website/package-lock.json, website/package.json
Integrated the website's Jest unit tests with Code Climate's dashboard and added its badge to the README.md.
Resolves #110
=> Added Code Climate test coverage

website/src/__tests__/helpers.test.js
Only sslAudioUrl() function so far.
=> Added the start of unit testing helpers.js

README.md, package-lock.json, package.json, website/package-lock.json, website/src/__tests__/About.test.js, website/src/__tests__/App.test.js, website/src/__tests__/Basicmock.test.js, website/src/__tests__/logo.test.js, website/src/__tests__/search.test.js, website/src/adapters/API.js, website/src/components/Header/Logo.js, website/src/config.js
=> Restore husky

README.md
Remove change directory that is no longer needed.
Add back comment above docker-compose command that was incorrectly removed.
=> Correct Run Locally Instructions

website/cypress/integration/search.spec.js, website/src/components/Header/Search.js
This is my first PR ever. I hope to feel accomplished, but suspect it will be an empty victory.
=> Removed quotes from URL

website/public/index.html
=> Added a description meta tag for SEO.  Closes #275

website/src/App.js, website/src/components/Main/SearchResults.js
- elements out of main pulled into main
- fixed left padding of search results
=> main and padding

website/cypress/integration/about.spec.js, website/cypress/integration/main.spec.js, website/cypress/integration/queue.spec.js
=> Added more a11y testing of pages within cypress
